### ISSUE TITLE
config

### ISSUE THREAD

**Issue by mutebessim** [linuxserver/libreelec-addons#44]
I need help.

Please give me example config file:

/storage/.kodi/userdata/addon_data/docker.linuxserver.letsencrypt/config

I want use nginx+php on LibreElec Wetek Play2.

**Comment by aptalca** [comment]
When you install the addon, it should create the default config files. But you have to fill in the rest of the settings such as url and subdomains.

**Comment by mutebessim** [comment]
Config file does not exist. Presumably, not working because of incompatible library. My kernel is 64bit, library is 32bit.

**Comment by aptalca** [comment]
Which build are you using? The 32bit addons should work on 64bit

**Comment by sparklyballs** [comment]
no response from user on this

i'm closing this one
