### ISSUE TITLE
Addon.zip fails to install

### ISSUE THREAD

**Issue by ngodber** [linuxserver/libreelec-addons#47]
Hi,

Figured I'd log this as I encountered it today. I'm running Kodi 17.6 on community build for S912 (aarch64).

Download and put on usb drive connected to SBC. Select install from zip but get a 'failed to install addon' 

kodi.log output:

13:43:55.589 T:4098230736   DEBUG: ------ Window Deinit (FileBrowser.xml) ------
13:43:55.612 T:4098230736   DEBUG: CAddonInstaller: installing from zip '/var/media/Xi/repository.linuxserver.docker.ext.zip'
13:43:55.613 T:4098230736   DEBUG: ZipManager: not a zip file!
13:43:55.614 T:4098230736   ERROR: GetDirectory - Error getting zip://%2fvar%2fmedia%2fXi%2frepository.linuxserver.docker.ext.zip/
13:43:55.645 T:4098230736   DEBUG: ------ Window Init (DialogNotification.xml) ------
13:44:01.420 T:4098230736   DEBUG: ------ Window Deinit (DialogNotification.xml) ------

**Comment by ngodber** [comment]
Tried downloading again, directly to linux drive encase it was some kind of windows mangling but still no joy.

**Comment by aptalca** [comment]
Somehow I missed this.

Honestly, it looks like the zip was not downloaded properly. Can you try manually extracting the zip to test?

**Comment by aptalca** [comment]
Haven't heard back, closing
