### ISSUE TITLE
[Request] sickchill docker

### ISSUE THREAD

**Issue by queeup** [linuxserver/libreelec-addons#48]
Please add sickchill docker to repo.

**Comment by aptalca** [comment]
This was an initial test repo. Libreelec did not want to add it to their official repo due to presence of piracy related addons. So we created the new one, which was added to libreelec: https://github.com/linuxserver/libreelec-addon-repo

This repo here hasn't really been maintained since then.

**Comment by queeup** [comment]
OK. Meanwhile I learned internals and I modified some of the add-ons here. I have some ideas and new addons.Maybe I will make some PRs? If it's going to be accepted and useful of course.

Closing this ticket now. Please tell me what do you think?

**Comment by aptalca** [comment]
@queeup do you wanna jump into our discord and ping me there so we can discuss?
https://discord.gg/YWrKVTn

**Comment by queeup** [comment]
Sure. I will.
